Airdrop cli
OnGridSystems/erc20_airdrop_cli pull request #1
Opened 2021-07-05 16:33 UTC by 999max

2021-07-07 14:37 UTC, ongrid requested changes
README.md should explain available commands

2021-07-07 14:37 UTC, ongrid commented on airdrop.py
> +    header = [['Address', 'Tokens', 'Nonce', 'Status']]
add Txn

2021-07-07 14:37 UTC, ongrid commented on airdrop.py
> +    token_contract = w3.eth.contract(address=Web3.toChecksumAddress("0x688ce8a97d5f1193261DB2271f542193D1dFd866"), abi=erc20_abi)
use cli command to set token address

2021-07-12 06:54 UTC, ongrid requested changes

2021-07-12 06:54 UTC, ongrid commented on test_airdrop.py
> +from ast import literal_eval
use json 
https://docs.python.org/3/library/json.html

2021-07-12 06:54 UTC, ongrid commented on test_airdrop.py
> +DBFILE = "db_test.sqlite"
:memory:

https://docs.peewee-orm.com/en/latest/peewee/database.html#using-sqlite

2021-07-12 12:01 UTC, 999max commented on test_airdrop.py
> +from ast import literal_eval
fixed

2021-07-12 13:25 UTC, ongrid approved these changes

2021-07-12 13:26 UTC, merged